<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(WindowsTargetFramework)</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\ReleaseSigning\afgc-release-public.pem" LogicalName="AFGCPCManager.ReleaseSigning.PublicKey.pem" />
  </ItemGroup>
</Project>
