<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(WindowsTargetFramework)</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>AFGCPCManager.UI</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\afgc-icon.png" LogicalName="AFGCPCManager.UI.Assets.afgc-icon.png" />
    <EmbeddedResource Include="Assets\afgc-icon.ico" LogicalName="AFGCPCManager.UI.Assets.afgc-icon.ico" />
  </ItemGroup>
</Project>
