using System.Drawing.Drawing2D;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;

namespace AFGCPCManager.UI;

public enum AfgcButtonKind { Primary, Secondary, Danger, Quiet }

public static class UiTheme
{
    public static readonly Color Canvas = Color.FromArgb(246, 247, 249);
    public static readonly Color Surface = Color.White;
    public static readonly Color SurfaceSubtle = Color.FromArgb(249, 250, 251);
    public static readonly Color Border = Color.FromArgb(218, 222, 230);
    public static readonly Color BorderStrong = Color.FromArgb(194, 201, 212);
    public static readonly Color Text = Color.FromArgb(29, 36, 48);
    public static readonly Color TextMuted = Color.FromArgb(99, 109, 126);
    public static readonly Color Primary = Color.FromArgb(47, 73, 149);
    public static readonly Color PrimaryHover = Color.FromArgb(38, 60, 127);
    public static readonly Color PrimarySoft = Color.FromArgb(235, 239, 250);
    public static readonly Color Success = Color.FromArgb(33, 122, 77);
    public static readonly Color SuccessSoft = Color.FromArgb(235, 247, 240);
    public static readonly Color Warning = Color.FromArgb(165, 95, 0);
    public static readonly Color WarningSoft = Color.FromArgb(255, 247, 230);
    public static readonly Color Danger = Color.FromArgb(180, 35, 24);
    public static readonly Color DangerHover = Color.FromArgb(145, 28, 20);
    public static readonly Color DangerSoft = Color.FromArgb(254, 243, 242);

    public static Font BodyFont => new("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
    public static Font SmallFont => new("Segoe UI", 8.25F, FontStyle.Regular, GraphicsUnit.Point);
    public static Font TitleFont => new("Segoe UI", 20F, FontStyle.Bold, GraphicsUnit.Point);
    public static Font DialogTitleFont => new("Segoe UI", 16F, FontStyle.Bold, GraphicsUnit.Point);
    public static Font SectionFont => new("Segoe UI Semibold", 11F, FontStyle.Bold, GraphicsUnit.Point);

    public static void Apply(Form form, bool centerParent = false)
    {
        // These forms are composed in code rather than generated by the WinForms
        // designer. Declare the logical design baseline explicitly; otherwise
        // WinForms records the monitor's current DPI as the baseline and leaves
        // every pixel-based bound unscaled while fonts render at the real DPI.
        form.AutoScaleDimensions = new SizeF(96F, 96F);
        form.AutoScaleMode = AutoScaleMode.Dpi;
        form.Font = BodyFont;
        form.BackColor = Canvas;
        form.ForeColor = Text;
        form.Icon = AfgcIcon.CreateIcon();
        form.StartPosition = centerParent ? FormStartPosition.CenterParent : FormStartPosition.CenterScreen;
    }

    public static Label Heading(string text, bool dialog = false) => new()
    {
        Text = text,
        AutoSize = true,
        Font = dialog ? DialogTitleFont : TitleFont,
        ForeColor = Text,
        Margin = Padding.Empty
    };

    public static Label SectionHeading(string text) => new()
    {
        Text = text,
        AutoSize = true,
        Font = SectionFont,
        ForeColor = Text,
        Margin = Padding.Empty
    };

    public static Label Body(string text, bool muted = false) => new()
    {
        Text = text,
        AutoSize = true,
        ForeColor = muted ? TextMuted : Text,
        Margin = Padding.Empty
    };

    public static PictureBox ProductMark(int size) => new()
    {
        Image = AfgcIcon.CreateBitmap(),
        Size = new Size(size, size),
        SizeMode = PictureBoxSizeMode.Zoom,
        Margin = Padding.Empty,
        TabStop = false
    };

    public static Panel Divider() => new()
    {
        Height = 1,
        Dock = DockStyle.Top,
        BackColor = Border,
        Margin = Padding.Empty
    };

    public static Panel FormHeader(string title, string subtitle, Control? actions = null,
        bool compact = false)
    {
        int markSize = compact ? 34 : 42;
        var text = new TableLayoutPanel
        {
            AutoSize = true,
            ColumnCount = 1,
            RowCount = 2,
            Margin = new Padding(14, compact ? 0 : 1, 0, 0)
        };
        text.Controls.Add(Heading(title, dialog: compact), 0, 0);
        var subtitleLabel = Body(subtitle, muted: true);
        subtitleLabel.Margin = new Padding(1, compact ? 2 : 4, 0, 0);
        text.Controls.Add(subtitleLabel, 0, 1);

        var identity = new FlowLayoutPanel
        {
            AutoSize = true,
            WrapContents = false,
            FlowDirection = FlowDirection.LeftToRight,
            Margin = Padding.Empty,
            Anchor = AnchorStyles.Left
        };
        identity.Controls.Add(ProductMark(markSize));
        identity.Controls.Add(text);

        var layout = new TableLayoutPanel
        {
            Dock = DockStyle.Fill,
            ColumnCount = actions is null ? 1 : 2,
            RowCount = 1,
            BackColor = Surface,
            Margin = Padding.Empty
        };
        layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
        if (actions is not null) layout.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
        layout.Controls.Add(identity, 0, 0);
        if (actions is not null)
        {
            actions.Anchor = AnchorStyles.Right;
            layout.Controls.Add(actions, 1, 0);
        }

        var header = new Panel
        {
            Dock = DockStyle.Top,
            Height = compact ? 84 : 104,
            Padding = compact ? new Padding(24, 18, 24, 18) : new Padding(28, 22, 28, 22),
            BackColor = Surface
        };
        header.Controls.Add(layout);
        return header;
    }

    public static FlowLayoutPanel ButtonRow(params Control[] controls)
    {
        var row = new FlowLayoutPanel
        {
            AutoSize = true,
            WrapContents = false,
            FlowDirection = FlowDirection.RightToLeft,
            Margin = Padding.Empty,
            Anchor = AnchorStyles.Right
        };
        foreach (Control control in controls) row.Controls.Add(control);
        return row;
    }

    public static Panel FormFooter(params Control[] controls)
    {
        var row = ButtonRow(controls);
        row.Dock = DockStyle.Fill;
        var footer = new Panel
        {
            Dock = DockStyle.Bottom,
            Height = 68,
            Padding = new Padding(24, 14, 24, 14),
            BackColor = Surface
        };
        footer.Controls.Add(row);
        footer.Controls.Add(Divider());
        return footer;
    }

    public static void StyleInput(Control control)
    {
        control.Font = BodyFont;
        control.BackColor = Surface;
        control.ForeColor = Text;
        control.Margin = new Padding(0, 6, 0, 12);
        if (control is TextBox textBox) textBox.BorderStyle = BorderStyle.FixedSingle;
        if (control is ComboBox comboBox)
        {
            comboBox.FlatStyle = FlatStyle.Flat;
            comboBox.IntegralHeight = false;
            void ApplyComboMetrics(object? _, EventArgs __) =>
                comboBox.DropDownHeight = Scale(comboBox, 240);
            comboBox.HandleCreated += ApplyComboMetrics;
            comboBox.DpiChangedAfterParent += ApplyComboMetrics;
            if (comboBox.IsHandleCreated) ApplyComboMetrics(null, EventArgs.Empty);
        }
    }

    public static void StyleProgressLog(TextBox textBox)
    {
        textBox.Font = new Font("Cascadia Mono", 8.5F, FontStyle.Regular, GraphicsUnit.Point);
        textBox.BackColor = SurfaceSubtle;
        textBox.ForeColor = Text;
        textBox.BorderStyle = BorderStyle.FixedSingle;
        textBox.Margin = new Padding(0, 12, 0, 0);
    }

    public static void StyleDataGrid(DataGridView grid)
    {
        grid.BackgroundColor = Surface;
        grid.BorderStyle = BorderStyle.None;
        grid.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
        grid.GridColor = Border;
        grid.EnableHeadersVisualStyles = false;
        grid.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
        grid.ColumnHeadersDefaultCellStyle = new DataGridViewCellStyle
        {
            BackColor = SurfaceSubtle,
            ForeColor = TextMuted,
            Font = new Font("Segoe UI Semibold", 8.5F, FontStyle.Bold),
            Padding = new Padding(12, 0, 12, 0),
            SelectionBackColor = SurfaceSubtle,
            SelectionForeColor = TextMuted
        };
        grid.DefaultCellStyle = new DataGridViewCellStyle
        {
            BackColor = Surface,
            ForeColor = Text,
            Font = BodyFont,
            Padding = new Padding(12, 0, 12, 0),
            SelectionBackColor = PrimarySoft,
            SelectionForeColor = Text
        };
        grid.RowHeadersVisible = false;
        grid.ColumnHeadersHeight = 38;
        grid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        grid.RowTemplate.Height = 48;
        grid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        grid.MultiSelect = false;
        grid.ReadOnly = true;
        grid.AllowUserToAddRows = false;
        grid.AllowUserToDeleteRows = false;
        grid.AllowUserToResizeRows = false;
        grid.AutoGenerateColumns = false;

        void ApplyGridMetrics(object? _, EventArgs __)
        {
            int horizontalPadding = Scale(grid, 12);
            grid.ColumnHeadersDefaultCellStyle.Padding =
                new Padding(horizontalPadding, 0, horizontalPadding, 0);
            grid.DefaultCellStyle.Padding =
                new Padding(horizontalPadding, 0, horizontalPadding, 0);
            grid.ColumnHeadersHeight = Scale(grid, 38);
            grid.RowTemplate.Height = Scale(grid, 48);
            foreach (DataGridViewRow row in grid.Rows)
                row.Height = grid.RowTemplate.Height;
        }
        grid.HandleCreated += ApplyGridMetrics;
        grid.DpiChangedAfterParent += ApplyGridMetrics;
        if (grid.IsHandleCreated) ApplyGridMetrics(null, EventArgs.Empty);
    }

    public static int Scale(Control control, int logicalPixels) =>
        Math.Max(1, (int)Math.Round(logicalPixels * control.DeviceDpi / 96F));

    internal static GraphicsPath RoundedRectangle(Rectangle bounds, int radius)
    {
        int diameter = Math.Min(radius * 2, Math.Min(bounds.Width, bounds.Height));
        var path = new GraphicsPath();
        if (diameter <= 0) { path.AddRectangle(bounds); return path; }
        var arc = new Rectangle(bounds.Location, new Size(diameter, diameter));
        path.AddArc(arc, 180, 90);
        arc.X = bounds.Right - diameter;
        path.AddArc(arc, 270, 90);
        arc.Y = bounds.Bottom - diameter;
        path.AddArc(arc, 0, 90);
        arc.X = bounds.Left;
        path.AddArc(arc, 90, 90);
        path.CloseFigure();
        return path;
    }
}

public sealed class AfgcButton : Button
{
    private const int LogicalHorizontalInset = 16;
    private const int LogicalVerticalInset = 8;
    private const int LogicalMinimumHeight = 38;
    private bool _hovered;
    [DefaultValue(AfgcButtonKind.Secondary)]
    public AfgcButtonKind Kind { get; set; }

    public AfgcButton(string text, AfgcButtonKind kind = AfgcButtonKind.Secondary)
    {
        Text = text;
        Kind = kind;
        FlatStyle = FlatStyle.Flat;
        FlatAppearance.BorderSize = 0;
        UseVisualStyleBackColor = false;
        AutoSize = true;
        AutoSizeMode = AutoSizeMode.GrowAndShrink;
        Padding = Padding.Empty;
        Margin = new Padding(8, 0, 0, 0);
        Cursor = Cursors.Hand;
        Font = UiTheme.BodyFont;
        SetStyle(ControlStyles.AllPaintingInWmPaint | ControlStyles.OptimizedDoubleBuffer |
                 ControlStyles.ResizeRedraw | ControlStyles.UserPaint, true);
    }

    public override Size GetPreferredSize(Size proposedSize)
    {
        Size text = TextRenderer.MeasureText(Text, Font, Size.Empty,
            TextFormatFlags.NoPadding | TextFormatFlags.NoPrefix |
            TextFormatFlags.SingleLine);
        int horizontalInset = LogicalToDeviceUnits(LogicalHorizontalInset);
        int verticalInset = LogicalToDeviceUnits(LogicalVerticalInset);
        int minimumHeight = LogicalToDeviceUnits(LogicalMinimumHeight);
        return new Size(
            text.Width + (horizontalInset * 2),
            Math.Max(minimumHeight, text.Height + (verticalInset * 2)));
    }

    protected override void OnMouseEnter(EventArgs e) { _hovered = true; Invalidate(); base.OnMouseEnter(e); }
    protected override void OnMouseLeave(EventArgs e) { _hovered = false; Invalidate(); base.OnMouseLeave(e); }
    protected override void OnEnabledChanged(EventArgs e) { Invalidate(); base.OnEnabledChanged(e); }

    protected override void OnPaint(PaintEventArgs e)
    {
        e.Graphics.SmoothingMode = SmoothingMode.AntiAlias;
        Rectangle bounds = ClientRectangle;
        bounds.Width--;
        bounds.Height--;
        (Color background, Color foreground, Color border) = Palette();
        using GraphicsPath path = UiTheme.RoundedRectangle(bounds, 6);
        using var brush = new SolidBrush(background);
        using var pen = new Pen(border);
        e.Graphics.FillPath(brush, path);
        e.Graphics.DrawPath(pen, path);
        Rectangle textBounds = Rectangle.Inflate(bounds,
            -LogicalToDeviceUnits(LogicalHorizontalInset), 0);
        TextRenderer.DrawText(e.Graphics, Text, Font, textBounds, foreground,
            TextFormatFlags.HorizontalCenter | TextFormatFlags.VerticalCenter |
            TextFormatFlags.SingleLine | TextFormatFlags.NoPrefix);
        if (Focused && ShowFocusCues)
        {
            Rectangle focus = Rectangle.Inflate(bounds, -4, -4);
            ControlPaint.DrawFocusRectangle(e.Graphics, focus, foreground, background);
        }
    }

    private (Color Background, Color Foreground, Color Border) Palette()
    {
        if (!Enabled) return (Color.FromArgb(239, 241, 244), Color.FromArgb(151, 158, 169), UiTheme.Border);
        return Kind switch
        {
            AfgcButtonKind.Primary => (_hovered ? UiTheme.PrimaryHover : UiTheme.Primary, Color.White,
                _hovered ? UiTheme.PrimaryHover : UiTheme.Primary),
            AfgcButtonKind.Danger => (_hovered ? UiTheme.DangerHover : UiTheme.Danger, Color.White,
                _hovered ? UiTheme.DangerHover : UiTheme.Danger),
            AfgcButtonKind.Quiet => (_hovered ? UiTheme.SurfaceSubtle : UiTheme.Surface, UiTheme.TextMuted,
                _hovered ? UiTheme.Border : UiTheme.Surface),
            _ => (_hovered ? UiTheme.SurfaceSubtle : UiTheme.Surface, UiTheme.Text, UiTheme.BorderStrong)
        };
    }
}

public sealed class AfgcCard : Panel
{
    public AfgcCard()
    {
        BackColor = UiTheme.Surface;
        Padding = new Padding(20);
        Margin = Padding.Empty;
        SetStyle(ControlStyles.AllPaintingInWmPaint | ControlStyles.OptimizedDoubleBuffer |
                 ControlStyles.ResizeRedraw | ControlStyles.UserPaint, true);
    }

    protected override void OnPaint(PaintEventArgs e)
    {
        e.Graphics.SmoothingMode = SmoothingMode.AntiAlias;
        Rectangle bounds = ClientRectangle;
        bounds.Width--;
        bounds.Height--;
        using GraphicsPath path = UiTheme.RoundedRectangle(bounds, 8);
        using var fill = new SolidBrush(BackColor);
        using var border = new Pen(UiTheme.Border);
        e.Graphics.FillPath(fill, path);
        e.Graphics.DrawPath(border, path);
    }
}

public sealed class AfgcTabControl : TabControl
{
    private int _metricsDpi = 96;

    public AfgcTabControl()
    {
        DrawMode = TabDrawMode.OwnerDrawFixed;
        SizeMode = TabSizeMode.Fixed;
        ItemSize = new Size(140, 38);
        Padding = new Point(16, 5);
        SetStyle(ControlStyles.OptimizedDoubleBuffer, true);
        HandleCreated += (_, _) => QueueDpiMetrics();
        DpiChangedAfterParent += (_, _) => ApplyDpiMetrics();
    }

    private void QueueDpiMetrics()
    {
        if (_metricsDpi == DeviceDpi || !IsHandleCreated) return;
        BeginInvoke(() =>
        {
            if (!IsDisposed) ApplyDpiMetrics();
        });
    }

    private void ApplyDpiMetrics()
    {
        _metricsDpi = DeviceDpi;
        ItemSize = new Size(UiTheme.Scale(this, 140), UiTheme.Scale(this, 38));
        Padding = new Point(UiTheme.Scale(this, 16), UiTheme.Scale(this, 5));
        Invalidate();
    }

    protected override void OnDrawItem(DrawItemEventArgs e)
    {
        bool selected = e.Index == SelectedIndex;
        Rectangle bounds = GetTabRect(e.Index);
        Color background = selected ? UiTheme.PrimarySoft : UiTheme.Surface;
        Color foreground = selected ? UiTheme.Primary : UiTheme.TextMuted;
        using var brush = new SolidBrush(background);
        e.Graphics.FillRectangle(brush, bounds);
        TextRenderer.DrawText(e.Graphics, TabPages[e.Index].Text, UiTheme.BodyFont, bounds,
            foreground, TextFormatFlags.HorizontalCenter | TextFormatFlags.VerticalCenter |
            TextFormatFlags.NoPrefix);
        if (selected)
        {
            using var pen = new Pen(UiTheme.Primary, 2);
            e.Graphics.DrawLine(pen, bounds.Left + 10, bounds.Bottom - 1,
                bounds.Right - 10, bounds.Bottom - 1);
        }
    }
}

public sealed class AfgcStatusBanner : Panel
{
    private readonly Label _message = new()
    {
        Dock = DockStyle.Fill,
        AutoEllipsis = true,
        TextAlign = ContentAlignment.MiddleLeft,
        Padding = new Padding(0),
        Font = UiTheme.BodyFont
    };
    private readonly StatusDot _dot = new();

    public AfgcStatusBanner()
    {
        Height = 54;
        Dock = DockStyle.Bottom;
        BackColor = UiTheme.Surface;
        Padding = new Padding(28, 0, 28, 0);
        Controls.Add(_message);
        Controls.Add(_dot);
        SetStyle(ControlStyles.AllPaintingInWmPaint | ControlStyles.OptimizedDoubleBuffer |
                 ControlStyles.ResizeRedraw | ControlStyles.UserPaint, true);
    }

    public void SetMessage(string value)
    {
        _message.Text = value;
        Color tone = DetermineTone(value);
        _message.ForeColor = tone == UiTheme.Danger ? UiTheme.Danger : UiTheme.TextMuted;
        _dot.SetTone(tone);
    }

    protected override void OnPaint(PaintEventArgs e)
    {
        using var pen = new Pen(UiTheme.Border);
        e.Graphics.DrawLine(pen, 0, 0, Width, 0);
    }

    private static Color DetermineTone(string value)
    {
        if (value.Contains("Running", StringComparison.OrdinalIgnoreCase)) return UiTheme.Success;
        if (value.Contains("failed", StringComparison.OrdinalIgnoreCase)
            || value.Contains("error", StringComparison.OrdinalIgnoreCase)
            || value.Contains("stopped", StringComparison.OrdinalIgnoreCase)) return UiTheme.Danger;
        if (value.Contains("required", StringComparison.OrdinalIgnoreCase)
            || value.Contains("unavailable", StringComparison.OrdinalIgnoreCase)
            || value.Contains("withheld", StringComparison.OrdinalIgnoreCase)) return UiTheme.Warning;
        return UiTheme.Primary;
    }

    private sealed class StatusDot : Panel
    {
        private Color _toneColor = UiTheme.Primary;
        public void SetTone(Color value) { _toneColor = value; Invalidate(); }

        public StatusDot()
        {
            Size = new Size(18, 18);
            Dock = DockStyle.Left;
            Margin = Padding.Empty;
            Padding = new Padding(0);
            BackColor = UiTheme.Surface;
        }

        protected override void OnPaint(PaintEventArgs e)
        {
            e.Graphics.SmoothingMode = SmoothingMode.AntiAlias;
            using var brush = new SolidBrush(_toneColor);
            e.Graphics.FillEllipse(brush,
                UiTheme.Scale(this, 3), UiTheme.Scale(this, 6),
                UiTheme.Scale(this, 7), UiTheme.Scale(this, 7));
        }
    }
}

public enum AfgcCalloutTone { Info, Warning, Danger }

public sealed class AfgcCallout : Panel
{
    private readonly Label _label = new()
    {
        Dock = DockStyle.Fill,
        AutoSize = false,
        Padding = new Padding(14, 10, 14, 10),
        Font = UiTheme.BodyFont
    };
    private AfgcCalloutTone _tone;

    [DefaultValue(AfgcCalloutTone.Info)]
    public AfgcCalloutTone Tone
    {
        get => _tone;
        set { _tone = value; ApplyTone(); }
    }

    [AllowNull]
    public override string Text
    {
        get => _label.Text;
        set { _label.Text = value ?? string.Empty; base.Text = value ?? string.Empty; }
    }

    public AfgcCallout(string text, AfgcCalloutTone tone = AfgcCalloutTone.Info)
    {
        Height = 56;
        Margin = Padding.Empty;
        Padding = new Padding(3, 0, 0, 0);
        Controls.Add(_label);
        HandleCreated += (_, _) => ApplyDpiMetrics();
        DpiChangedAfterParent += (_, _) => ApplyDpiMetrics();
        _tone = tone;
        Text = text;
        ApplyTone();
    }

    private void ApplyDpiMetrics()
    {
        Padding = new Padding(UiTheme.Scale(this, 3), 0, 0, 0);
        int horizontal = UiTheme.Scale(this, 14);
        int vertical = UiTheme.Scale(this, 10);
        _label.Padding = new Padding(horizontal, vertical, horizontal, vertical);
    }

    private void ApplyTone()
    {
        (Color accent, Color background) = _tone switch
        {
            AfgcCalloutTone.Warning => (UiTheme.Warning, UiTheme.WarningSoft),
            AfgcCalloutTone.Danger => (UiTheme.Danger, UiTheme.DangerSoft),
            _ => (UiTheme.Primary, UiTheme.PrimarySoft)
        };
        BackColor = accent;
        _label.BackColor = background;
        _label.ForeColor = _tone == AfgcCalloutTone.Danger ? UiTheme.Danger : UiTheme.Text;
    }
}
