<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(WindowsTargetFramework)</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Nefarius.ViGEm.Client" />
    <ProjectReference Include="..\AFGCPCManager.Core\AFGCPCManager.Core.csproj" />
  </ItemGroup>
</Project>
