<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(WindowsTargetFramework)</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>AFGCPCManager.UiPreview</AssemblyName>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>..\..\src\AFGCPCManager.UI\Assets\afgc-icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\AFGCPCManager.App\AFGCPCManager.App.csproj" />
    <ProjectReference Include="..\..\installer\AFGCPCManager.Bootstrapper\AFGCPCManager.Bootstrapper.csproj" />
    <ProjectReference Include="..\..\installer\AFGCPCManager.Uninstaller\AFGCPCManager.Uninstaller.csproj" />
  </ItemGroup>
</Project>
