<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>$(WindowsTargetFramework)</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>AFGCPCManager.Uninstaller</AssemblyName>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>..\..\src\AFGCPCManager.UI\Assets\afgc-icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AFGCPCManager.Setup.Core\AFGCPCManager.Setup.Core.csproj" />
    <ProjectReference Include="..\..\src\AFGCPCManager.UI\AFGCPCManager.UI.csproj" />
  </ItemGroup>
</Project>
