<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(WindowsTargetFramework)</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\AFGCPCManager.Windows\AFGCPCManager.Windows.csproj" />
  </ItemGroup>
</Project>
